# Generated by Django 5.0 on 2023-12-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_distributors_details',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
