# Generated by Django 5.0 on 2023-12-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0003_fin_staff_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Modules_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.IntegerField(default=0, null=True)),
                ('Price_List', models.IntegerField(default=0, null=True)),
                ('Stock_Adjustment', models.IntegerField(default=0, null=True)),
                ('Cash_in_hand', models.IntegerField(default=0, null=True)),
                ('Offline_Banking', models.IntegerField(default=0, null=True)),
                ('Bank_Reconciliation', models.IntegerField(default=0, null=True)),
                ('UPI', models.IntegerField(default=0, null=True)),
                ('Bank_Holders', models.IntegerField(default=0, null=True)),
                ('Cheque', models.IntegerField(default=0, null=True)),
                ('Loan_Account', models.IntegerField(default=0, null=True)),
                ('Customers', models.IntegerField(default=0, null=True)),
                ('Invoice', models.IntegerField(default=0, null=True)),
                ('Estimate', models.IntegerField(default=0, null=True)),
                ('Sales_Order', models.IntegerField(default=0, null=True)),
                ('Recurring_Invoice', models.IntegerField(default=0, null=True)),
                ('Retainer_Invoice', models.IntegerField(default=0, null=True)),
                ('Credit_Note', models.IntegerField(default=0, null=True)),
                ('Payment_Received', models.IntegerField(default=0, null=True)),
                ('Delivery_Challan', models.IntegerField(default=0, null=True)),
                ('Vendors', models.IntegerField(default=0, null=True)),
                ('Bills', models.IntegerField(default=0, null=True)),
                ('Recurring_Bills', models.IntegerField(default=0, null=True)),
                ('Debit_Note', models.IntegerField(default=0, null=True)),
                ('Purchase_Order', models.IntegerField(default=0, null=True)),
                ('Expenses', models.IntegerField(default=0, null=True)),
                ('Recurring_Expenses', models.IntegerField(default=0, null=True)),
                ('Payment_Made', models.IntegerField(default=0, null=True)),
                ('EWay_Bill', models.IntegerField(default=0, null=True)),
                ('Chart_of_Accounts', models.IntegerField(default=0, null=True)),
                ('Manual_Journal', models.IntegerField(default=0, null=True)),
                ('Employees', models.IntegerField(default=0, null=True)),
                ('Employees_Loan', models.IntegerField(default=0, null=True)),
                ('Holiday', models.IntegerField(default=0, null=True)),
                ('Attendance', models.IntegerField(default=0, null=True)),
                ('Salary_Details', models.IntegerField(default=0, null=True)),
                ('update_action', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fin_company_details',
            name='Accountant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fin_company_details',
            name='Payment_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
