# Generated by Django 5.0 on 2023-12-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_fin_modules_list_fin_company_details_accountant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_company_details',
            name='Business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fin_company_details',
            name='Company_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fin_company_details',
            name='Industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fin_modules_list',
            name='Login_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details'),
        ),
        migrations.AddField(
            model_name='fin_modules_list',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details'),
        ),
    ]
