# Generated by Django 5.0 on 2023-12-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0005_fin_company_details_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_modules_list',
            name='Reconcile',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
