# Generated by Django 5.0 on 2023-12-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0006_fin_modules_list_reconcile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_staff_details',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
