# Generated by Django 5.0 on 2024-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0010_fin_anotification_modules_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_anotification',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
