# Generated by Django 5.0 on 2024-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0011_fin_anotification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_anotification',
            name='Noti_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
