# Generated by Django 5.0 on 2024-01-04 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0012_fin_anotification_noti_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_DNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Discription', models.CharField(blank=True, max_length=255, null=True)),
                ('Noti_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
                ('Login_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Modules_List', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_modules_list')),
                ('PaymentTerms_updation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_payment_terms_updation')),
            ],
        ),
    ]
