# Generated by Django 5.0 on 2024-01-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0013_fin_dnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_dnotification',
            name='Distributor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_distributors_details'),
        ),
    ]
