# Generated by Django 5.0 on 2024-01-05 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0014_fin_dnotification_distributor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_CNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Discription', models.CharField(blank=True, max_length=255, null=True)),
                ('Noti_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
                ('Company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Login_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
    ]
