# Generated by Django 3.2.23 on 2024-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0015_fin_cnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_company_details',
            name='GST_NO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
