# Generated by Django 3.2.23 on 2024-01-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0016_alter_fin_company_details_gst_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Chart_Of_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_card_no', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_account', models.BooleanField(blank=True, default=False, null=True)),
                ('parent_account', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_no', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('create_status', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('hsn', models.BigIntegerField(blank=True, null=True)),
                ('tax_reference', models.CharField(max_length=100, null=True)),
                ('intra_state_tax', models.IntegerField(default=0, null=True)),
                ('inter_state_tax', models.IntegerField(default=0, null=True)),
                ('sales_account', models.CharField(max_length=100, null=True)),
                ('selling_price', models.FloatField(default=0.0, null=True)),
                ('sales_description', models.CharField(max_length=100, null=True)),
                ('purchase_account', models.CharField(max_length=100, null=True)),
                ('purchase_price', models.FloatField(default=0.0, null=True)),
                ('purchase_description', models.CharField(max_length=100, null=True)),
                ('item_created', models.DateField(auto_now_add=True, null=True)),
                ('min_stock', models.IntegerField(default=0, null=True)),
                ('inventory_account', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('current_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_in', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_out', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_unit_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(default='Active', max_length=100, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Items_Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Items_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_ChartOfAccount_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_chart_of_account')),
            ],
        ),
    ]
