# Generated by Django 3.2.23 on 2024-01-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0017_fin_chart_of_account_fin_chartofaccount_history_fin_items_fin_items_comments_fin_items_transaction_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_cnotification',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items'),
        ),
    ]
