# Generated by Django 3.2.23 on 2024-01-17 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0018_fin_cnotification_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('Account_number', models.CharField(max_length=15)),
                ('Ifsc_code', models.CharField(max_length=11)),
                ('Swift_code', models.CharField(max_length=11)),
                ('Bank_name', models.CharField(choices=[('SBI', 'State Bank of India'), ('BOB', 'Bank of Baroda'), ('BOI', 'Bank of India'), ('BOM', 'Bank of Maharashtra'), ('CAN', 'Canara Bank'), ('CBI', 'Central Bank of India'), ('IND', 'Indian Bank'), ('IOB', 'Indian Overseas Bank'), ('PSB', 'Punjab & Sind Bank'), ('PNB', 'Punjab National Bank'), ('UCO', 'UCO Bank'), ('UBI', 'Union Bank of India'), ('AXIS', 'Axis Bank Ltd.'), ('BANDHAN', 'Bandhan Bank Ltd.'), ('CSB', 'CSB Bank Limited'), ('CUB', 'City Union Bank Ltd.'), ('DCB', 'DCB Bank Ltd.'), ('DHANLAXMI', 'Dhanlaxmi Bank Ltd.'), ('FEDERAL', 'Federal Bank Ltd.'), ('HDFC', 'HDFC Bank Ltd.'), ('ICICI', 'ICICI Bank Ltd.')], max_length=10)),
                ('Branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_BankAccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Alias', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('Account_type', models.CharField(choices=[('CC', 'Credit Card'), ('BA', 'Bank Account')], default='BA', max_length=20)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('ArithmeticErrormount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Open_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], default='unknown', max_length=20)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Holder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccountholder')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_MailingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mailing_name', models.CharField(max_length=100)),
                ('Address', models.TextField(blank=True, max_length=255, null=True)),
                ('Country', django_countries.fields.CountryField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chhattisgarh'), ('DL', 'National Capital Territory of Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('LA', 'Ladakh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UT', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=100)),
                ('Pin', models.CharField(max_length=6)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Holder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccountholder')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Holder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccountholder')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_BankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pan_it_number', models.CharField(blank=True, max_length=10)),
                ('Registration_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('consumer', 'Consumer'), ('unregistered', 'Unregistered')], default='unknown', max_length=20)),
                ('Gstin_un', models.CharField(blank=True, max_length=15)),
                ('Set_alter_gst_details', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Holder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccountholder')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_BankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Holder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccountholder')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_BankConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Set_cheque_book_range', models.BooleanField(default=False)),
                ('Enable_cheque_printing', models.BooleanField(default=False)),
                ('Set_cheque_printing_configuration', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Holder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccountholder')),
                ('LoginDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.AddField(
            model_name='fin_bankaccount',
            name='Holder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_bankaccountholder'),
        ),
        migrations.AddField(
            model_name='fin_bankaccount',
            name='LoginDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details'),
        ),
    ]
