# Generated by Django 3.2.23 on 2024-01-18 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0021_alter_fin_openingbalance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_openingbalance',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
