# Generated by Django 3.2.23 on 2024-01-19 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0022_alter_fin_openingbalance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(blank=True, upload_to='file/')),
                ('upload_image', models.ImageField(blank=True, upload_to='media/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employee_salary_type', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_details', models.CharField(blank=True, max_length=10, null=True)),
                ('salary_effective_from', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_head', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_amount', models.FloatField(blank=True, null=True)),
                ('amount_per_hour', models.IntegerField(blank=True, null=True)),
                ('total_working_hours', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name_mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('provide_bank_details', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tds_applicable', models.CharField(blank=True, max_length=255, null=True)),
                ('tds_type', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage_amount', models.IntegerField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=255, null=True)),
                ('income_tax_number', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=255, null=True)),
                ('universal_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pf_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pr_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('esi_number', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_street', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_city', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_state', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_country', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date(2024, 1, 19))),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.employee')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('holiday_name', models.CharField(blank=True, max_length=255, null=True)),
                ('holiday_days', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.employee')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date(2024, 1, 19))),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.employee')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
    ]
