# Generated by Django 3.2.23 on 2024-01-25 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0025_auto_20240124_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_bankaccountholder',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_bankaccountholder',
            name='LoginDetails',
        ),
        migrations.RemoveField(
            model_name='fin_bankconfiguration',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_bankconfiguration',
            name='Holder_id',
        ),
        migrations.RemoveField(
            model_name='fin_bankconfiguration',
            name='LoginDetails',
        ),
        migrations.RemoveField(
            model_name='fin_bankhistory',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_bankhistory',
            name='Holder_id',
        ),
        migrations.RemoveField(
            model_name='fin_bankhistory',
            name='LoginDetails',
        ),
        migrations.RemoveField(
            model_name='fin_bankhistory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='fin_bankingdetails',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_bankingdetails',
            name='Holder_id',
        ),
        migrations.RemoveField(
            model_name='fin_bankingdetails',
            name='LoginDetails',
        ),
        migrations.RemoveField(
            model_name='fin_comment',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_comment',
            name='Holder_id',
        ),
        migrations.RemoveField(
            model_name='fin_comment',
            name='LoginDetails',
        ),
        migrations.RemoveField(
            model_name='fin_comment',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='fin_mailingaddress',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_mailingaddress',
            name='Holder_id',
        ),
        migrations.RemoveField(
            model_name='fin_mailingaddress',
            name='LoginDetails',
        ),
        migrations.RemoveField(
            model_name='fin_openingbalance',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='fin_openingbalance',
            name='Holder_id',
        ),
        migrations.RemoveField(
            model_name='fin_openingbalance',
            name='LoginDetails',
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 25)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 25)),
        ),
        migrations.DeleteModel(
            name='Fin_BankAccount',
        ),
        migrations.DeleteModel(
            name='Fin_BankAccountHolder',
        ),
        migrations.DeleteModel(
            name='Fin_BankConfiguration',
        ),
        migrations.DeleteModel(
            name='Fin_BankHistory',
        ),
        migrations.DeleteModel(
            name='Fin_BankingDetails',
        ),
        migrations.DeleteModel(
            name='Fin_Comment',
        ),
        migrations.DeleteModel(
            name='Fin_MailingAddress',
        ),
        migrations.DeleteModel(
            name='Fin_OpeningBalance',
        ),
    ]
