# Generated by Django 3.2.23 on 2024-01-27 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0026_auto_20240125_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 27)),
        ),
        migrations.AlterField(
            model_name='fin_bankholder',
            name='Swift_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 27)),
        ),
    ]
