# Generated by Django 5.0.1 on 2024-02-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0032_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fin_Attendance',
            new_name='Fin_Attendances',
        ),
    ]
